version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "installing something"     
  pre_build:
    commands:
      - echo "we are in the pre_build phase..."
  build:
    commands:
      - echo "We are in the build block"
      - echo "We will run some tests"
      - grep -Fq "Test app for AWS CodePipeline" index.html
  post_build:
    commands:
      - echo "Build completed"
      
artifacts:
  files:
    - '**/*'